var math = require('mathjs');
console.log(eval('math.matrix([[3,4],[1,2]]);'));
var B=[1,7];
console.log(eval('[1,2];'));
console.log(eval('[4,4,4];'));
// %% boooooo
console.log(eval('math.matrix([[1,1],[1,1]]);'));

//generated by matlab-node utility