'use strict';
var fs = require('fs');

exports.runMatlab = function(matlabFile) {
  fs.readFile(matlabFile, function (err,data) {
  if (err) {
    return console.log(err.message);
  }
  
// write an output file and append 
var fileOutput=matlabFile.split('.m');
// overwrite if already exist
var logStream = fs.createWriteStream(fileOutput[0] +'.js', {'flags': 'w'});
var logStream = fs.createWriteStream(fileOutput[0] +'.js', {'flags': 'a'});
var n = '\n';
// first module to import
logStream.write("var math = require('mathjs');" + n);
var array = data.toString().split('\n');

    for(var i in array) {
		// eliminate space
		var line=array[i];
		
		//var line=array[i].replace(/ /g,'');
		// control if contains a substring and return is index else -1
		if (line.indexOf('matrix')!=-1 || line.indexOf('[')!=-1){
			require ('./util/matrix.js')(line,logStream);
		}
		if (line.indexOf('%')!=-1){
			line = '// ' + line;
			logStream.write(line + n);
		}
		
    };
	logStream.end('\n//generated by matlab-node utility');
});
  
  
}